services:
  vuzon:
    container_name: vuzon
    image: ghcr.io/kernel-nomad/vuzon
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "${VUZON_PORT:-8001}:8001"
    volumes:
      - ./sessions:/app/sessions
